version: '3.8'

services:
  contactsApp:
    container_name: contactsApp
    image: mongo:latest
    environment:
      - MOMGO_DATABASE="nedufari"
    ports:
      - 27017:27017


  mongo-express:
    container_name: mongo-express1
    image: mongo-express
    environment:
      - ME_CONFIG_MOGODB_SERVER=contactsApp
      - ME_CONFIG_MOGODB_PORT=27017
    depends_on:
      - contactsApp
    ports:
      - 8081:8081


